version: '2'

services:
        ordering:
                container_name: ordering_service
                build: ./OrderingService
                ports:
                        - "80:80"
        monitoring:
                container_name: monitoring_service
                build: ./MonitoringService
                ports:
                        - "8080:8080"
