version: '3'

services:
        ordering:
                container_name: ordering_service
                build: ./OrderingService
                volumes:
                        - "my-log:/SE3Project/OrderingService/my-log"
                ports:
                        - "80:80"
        monitoring:
                container_name: monitoring_service
                build: ./MonitoringService
                volumes:
                        - "my-log:/SE3Project/MonitoringService/my-log:ro"                
                ports:
                        - "8080:8080"
        inventory:
                container_name: fake_inventory_service
                build: ./FakeInventoryService
                ports:
                        - "8082:8082"
        user:
                container_name: fake_user_service
                build: ./FakeUserService
                ports:
                        - "8084:8084"
volumes:
        my-log:
                external: false
                          
                          
