version: '2'

services:
        ordering:
                container_name: ordering_service
                build: ./OrderingService
                volumes:
                        - "my-log:/SE3Project/OrderingService/my-log"
                ports:
                        - "80:80"
        monitoring:
                container_name: monitoring_service
                build: ./MonitoringService
                volumes:
                        - "my-log:/SE3Project/MonitoringService/my-log:ro"                
                ports:
                        - "8080:8080"
volumes:
        my-logs:
                external: false
                          
                          
